### ISSUE TITLE
Problem with kodi 15

### ISSUE THREAD

**Issue by ghost** [mintsoft/xbmc.plugin.makemkvbluray#1]
Tried current zip with kodi 15 (isengard).  Error message is "Add-on does not have the correct structure".  I need to use kodi 15 for closed caption support on live tv.  Do you have any suggestions.

**Comment by mintsoft** [comment]
@brombo I'll have a look!

**Comment by mintsoft** [comment]
@brombo Which O/S are you running Kodi 15 on? I've just tested it on my Windows test install and it loads from the zip without issue

**Comment by mintsoft** [comment]
@brombo Interesting; I run my actual media centre on 14.04 and haven't had that particular problem.

I have had problems installing some addons from time-to-time that is (this just sounds so ridiculous) 'fixed' by renaming them from `plugin.x.y.zip` to `plugin.x.y-1.0.0.zip`, can you try that?

**Comment by ghost** [comment]
On 07/18/2015 10:24 AM, Rob Emery wrote:

> @brombo https://github.com/brombo Interesting; I run my actual media 
> centre on 14.04 and haven't had that particular problem.
> 
> I have had problems installing some addons from time-t- time that is 
> (this just sounds so ridiculous) 'fixed' by renaming them from 
> |plugin.x.y.zip| to |plugin.x.y-1.0.0.zip|, can you try that?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mintsoft/xbmc.plugin.makemkvbluray/issues/1#issuecomment-122548738.
> 
> Did not work.  I uninstalled and reinstalled kodi and libaacs and tried 
> again with no luck.  More system info (from kodi system info)-

Ubuntu 14.04.2 LTS (kernel: Linux 3.16.0-43-generic)

Kodi 15.0-RC2 Git:0aa930b (Compiled: Jul 11 2015)

---

MakeMKV v1.9.1 [linux(x64-release)]

License type: Registered

This version expirers: Never

**Comment by mintsoft** [comment]
I've just updated my media centre onto the exact same version and loaded the zip from the repo first time no problems.

I'd suggest having a look in `~/.kodi/addons` and deleting `plugin.makemkvbluray`, if it exists. If it still doesn't work I'd try removing the entire `.kodi` directory (this will delete your kodi library and settings etc) and see if it works. Other than that I'm pretty much out of ideas!

**Comment by mintsoft** [comment]
That error sounds like the un-forked version of the addon, are you definitely using the zip from: https://github.com/mintsoft/xbmc.plugin.makemkvbluray/raw/master/plugin.makemkvbluray.zip

**Comment by mintsoft** [comment]
Ah I think I understand the problem. The fork I maintain has been gutted for all functionality except playing from `makemkvcon stream` running somewhere (personally I have this running on my server). For local playback I think the latest version (from this thread: http://forum.kodi.tv/showthread.php?tid=67420 which is the original source) is: https://github.com/X-dark/plugin.makemkvbluray/archive/1.1.3.zip

**Comment by mintsoft** [comment]
You may also have luck with this option: http://forum.kodi.tv/showthread.php?tid=173474 however I've never used it!

**Comment by mintsoft** [comment]
Aha, that explains it! Good to hear either way
